"use client";

import * as React from "react";
import { ArrowUpRight, Send, Sparkles } from "lucide-react";

/**
 * Illustrative preview of the SIRIS patient-education experience
 * (https://siris-1029209978489.us-central1.run.app). The live tool is a
 * specialty-focused education assistant that helps patients prepare questions
 * and navigate Mayo Clinic resources. The exchanges below are generic,
 * preparation-oriented examples — not clinical guidance and not generated by
 * the live model. Real, personalized answers come from the deployed tool.
 */

type Exchange = {
  question: string;
  answer: string;
  resources: string[];
  followUps: string[];
};

const EXCHANGES: Record<string, Exchange> = {
  "What should I ask before bariatric surgery?": {
    question: "What should I ask before bariatric surgery?",
    answer:
      "It helps to ask which procedure fits your health profile, what recovery looks like week by week, how your current medications may change, and what long-term follow-up involves. SIRIS can turn these into a personalized list to bring to your appointment.",
    resources: ["Preparing for surgery", "Procedure overview"],
    followUps: ["What does recovery look like?", "How will my diet change?"],
  },
  "How should I prepare for my consultation?": {
    question: "How should I prepare for my consultation?",
    answer:
      "Bring your current medication list, any recent lab results, and the questions that matter most to you. Noting your goals and concerns ahead of time makes the conversation with your care team more productive.",
    resources: ["Consultation checklist", "What to bring"],
    followUps: ["What should I ask before bariatric surgery?"],
  },
  "What does recovery look like?": {
    question: "What does recovery look like?",
    answer:
      "Recovery varies by person and procedure. Mayo Clinic education materials walk through the typical timeline, activity guidance, and the stages of returning to a normal diet. SIRIS can point you to the resources that match your procedure.",
    resources: ["Recovery timeline", "Activity guidance"],
    followUps: ["How will my diet change?"],
  },
  "How will my diet change?": {
    question: "How will my diet change?",
    answer:
      "Most procedures move through staged nutrition phases over the first weeks and months. The specifics depend on your plan, so SIRIS surfaces the Mayo Clinic nutrition resources for your procedure and flags questions worth raising with your dietitian.",
    resources: ["Nutrition stages", "Dietitian questions"],
    followUps: ["How should I prepare for my consultation?"],
  },
};

const STARTERS = [
  "What should I ask before bariatric surgery?",
  "How should I prepare for my consultation?",
];

export function SirisDemo({ liveUrl }: { liveUrl: string }) {
  const [thread, setThread] = React.useState<Exchange[]>([EXCHANGES[STARTERS[0]]]);
  const scrollRef = React.useRef<HTMLDivElement>(null);

  const suggestions = React.useMemo(() => {
    const asked = new Set(thread.map((e) => e.question));
    const last = thread[thread.length - 1];
    const pool = [...(last?.followUps ?? []), ...STARTERS];
    return pool.filter((q) => !asked.has(q) && EXCHANGES[q]).slice(0, 3);
  }, [thread]);

  const ask = (question: string) => {
    const exchange = EXCHANGES[question];
    if (!exchange) return;
    setThread((prev) => [...prev, exchange]);
  };

  React.useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [thread]);

  return (
    <div className="card-glass overflow-hidden rounded-xl">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-4">
        <div className="flex items-center gap-2.5">
          <span className="flex h-8 w-8 items-center justify-center rounded-md border border-[#64B5F6]/30 bg-[#64B5F6]/10">
            <Sparkles className="h-4 w-4 text-[#64B5F6]" aria-hidden="true" />
          </span>
          <div>
            <p className="text-sm font-semibold text-white">SIRIS</p>
            <p className="text-[11px] text-white/45">Surgical patient education</p>
          </div>
        </div>
        <span className="rounded-full border border-white/10 bg-white/[0.03] px-2.5 py-1 font-mono text-[10px] uppercase tracking-widest text-white/45">
          Illustrative preview
        </span>
      </div>

      {/* Chat thread */}
      <div ref={scrollRef} className="max-h-80 space-y-4 overflow-y-auto bg-[#000814] px-5 py-5">
        {thread.map((exchange, i) => (
          <div key={`${exchange.question}-${i}`} className="space-y-3">
            {/* Patient question */}
            <div className="flex justify-end">
              <p className="max-w-[80%] rounded-2xl rounded-br-sm bg-[#64B5F6]/15 px-3.5 py-2 text-sm text-white">
                {exchange.question}
              </p>
            </div>
            {/* SIRIS answer */}
            <div className="flex justify-start">
              <div className="max-w-[88%] space-y-3 rounded-2xl rounded-bl-sm border border-white/10 bg-white/[0.03] px-3.5 py-3">
                <p className="text-sm leading-relaxed text-white/75">{exchange.answer}</p>
                <div className="flex flex-wrap gap-1.5">
                  {exchange.resources.map((r) => (
                    <span
                      key={r}
                      className="rounded-md border border-[#64B5F6]/20 bg-[#64B5F6]/5 px-2 py-0.5 text-[11px] text-[#9bcbf0]"
                    >
                      {r}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Suggested questions */}
      <div className="border-t border-white/10 bg-[#000814] px-5 py-4">
        {suggestions.length > 0 ? (
          <>
            <p className="mb-2.5 font-mono text-[10px] uppercase tracking-widest text-white/40">
              Suggested questions
            </p>
            <div className="flex flex-wrap gap-2">
              {suggestions.map((q) => (
                <button
                  key={q}
                  type="button"
                  onClick={() => ask(q)}
                  className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.02] px-3 py-1.5 text-xs font-medium text-white/65 transition-colors hover:border-[#64B5F6]/40 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#64B5F6]/70"
                >
                  <Send className="h-3 w-3" aria-hidden="true" />
                  {q}
                </button>
              ))}
            </div>
          </>
        ) : (
          <p className="text-xs text-white/45">
            That is the end of this short preview. Open SIRIS for the full, personalized experience.
          </p>
        )}
      </div>

      {/* Footer */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 px-5 py-4">
        <p className="max-w-md text-xs leading-relaxed text-white/40">
          Example interactions for illustration only. SIRIS supports preparation and resource
          navigation; it does not provide diagnosis or replace your care team.
        </p>
        <a
          href={liveUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex shrink-0 items-center gap-1.5 rounded-md bg-[#64B5F6] px-4 py-2 text-sm font-semibold text-[#001018] transition-opacity hover:opacity-90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#64B5F6]/70"
        >
          Open SIRIS
          <ArrowUpRight className="h-4 w-4" aria-hidden="true" />
        </a>
      </div>
    </div>
  );
}
